name: DevSecOps Pipeline PHP/MySQL
on: [push, pull_request]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with: { php-version: '8.2' }
    - name: Composer Audit (deps vuln)
      run: composer audit --locked
    - name: PHPStan (SAST)
      run: composer require --dev phpstan/phpstan && ./vendor/bin/phpstan analyse
    - name: OWASP ZAP Scan (DAST)
      uses: zaproxy/action-full-scan@v0.4.0
      with:
        target: 'http://localhost:8080'  # À adapter post-build

  build-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: gtf
        ports:
          - 3306:3306
    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with: { php-version: '8.2', extensions: mysql,pdo }
    - run: composer install --no-progress
    - run: composer test  # PHPUnit ou vos tests
    - name: Docker Build
      run: docker build -t projet-gestion .

  deploy-staging:
    needs: [security-scan, build-test]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Render/Heroku
      uses: akhileshns/heroku-deploy@v3.12.14  # Exemple Heroku
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "votre-app-staging"
        heroku_email: "votre@email.com"
